[profile.default]
via-ir = true
fs_permissions = [{ access = "read", path = "./"}]
names = true
sizes = true
libs = ["node_modules", "lib"]

[fuzz]
runs = 64

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
