[profile.default]
fs_permissions = [{ access = "read", path = "./"}]
names = true
sizes = true
libs = ["node_modules", "lib"]

[profile.ci.fuzz]
runs = 512

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
