[profile.default]
names = true
sizes = true
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./config/"}]

[fuzz]
runs = 16


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
