name: Forge checks

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    paths:
      - lib/**
      - src/**
      - foundry.toml
      - remappings.txt
      - .github/actions/forge-build/**
      - .github/workflows/forge-compilation.yml

env:
  FOUNDRY_PROFILE: ci

jobs:
  compilation:
    name: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}

      - uses: ./.github/actions/forge-build
