name: Pull request

on:
  pull_request:
    branches-ignore: # already triggered by push
      - main
      - dev
    paths:
      - lib/**
      - src/**
      - foundry.toml
      - remappings.txt
      - .github/workflows/pull_request.yml

jobs:
  test-ethereum-mainnet:
    name: Tests (ethereum-mainnet)

    uses: morpho-dao/morpho-aave-v3/.github/workflows/forge.yml@main
    with:
      network: ethereum-mainnet
    secrets: inherit
