name: Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  forge-ethereum-mainnet:
    name: Forge

    uses: ./.github/workflows/forge.yml
    with:
      network: ethereum-mainnet
      internal-fuzz-runs: 64
      integration-fuzz-runs: 64
      invariant-depth: 256
    secrets: inherit
